.base-template:
  image: node:24-slim
  before_script:
    - corepack enable
    - corepack prepare pnpm@latest --activate
    - pnpm config set store-dir .pnpm-store
    - pnpm install
  cache:
    key:
      files:
        - pnpm-lock.yaml
    paths:
      - .pnpm-store

.release-template:
  image: docker:29.2
  services:
    - docker:29.2-dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $GITLAB_PERSONAL_ACCESS_TOKEN $CI_REGISTRY
