include:
  - '.gitlab/.before-script-template.yml'

pre-checks:
  extends: .base-template
  stage: pre-checks
  when: always
  script:
    - pnpm run type-check
    - pnpm run lint-check
    - pnpm run test
    - pnpm run build
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

update-coverage-badge:
  extends: .base-template
  stage: pre-checks
  when: always
  variables:
    HUSKY: 0
  script:
    - pnpm run test:coverage:readme
    - git config user.email "ci@gitlab.com"
    - git config user.name "GitLab CI"
    - git add README.md
    - git diff --cached --quiet || git commit --no-verify -m "chore: update coverage table in README [skip ci]"
    - git push "https://gitlab-ci-token:${GITLAB_PERSONAL_ACCESS_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git" HEAD:${CI_DEFAULT_BRANCH}
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
