/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './pages/__root'
import { Route as DefaultRouteImport } from './pages/_default'
import { Route as AuthRouteImport } from './pages/_auth'

const DefaultIndexLazyRouteImport = createFileRoute('/_default/')()
const DefaultAboutUsLazyRouteImport = createFileRoute('/_default/about-us')()
const AuthDashboardLazyRouteImport = createFileRoute('/_auth/dashboard')()

const DefaultRoute = DefaultRouteImport.update({
  id: '/_default',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DefaultIndexLazyRoute = DefaultIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DefaultRoute,
} as any).lazy(() => import('./pages/_default.index.lazy').then((d) => d.Route))
const DefaultAboutUsLazyRoute = DefaultAboutUsLazyRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => DefaultRoute,
} as any).lazy(() =>
  import('./pages/_default.about-us.lazy').then((d) => d.Route),
)
const AuthDashboardLazyRoute = AuthDashboardLazyRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./pages/_auth.dashboard.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/dashboard': typeof AuthDashboardLazyRoute
  '/about-us': typeof DefaultAboutUsLazyRoute
  '/': typeof DefaultIndexLazyRoute
}
export interface FileRoutesByTo {
  '/dashboard': typeof AuthDashboardLazyRoute
  '/about-us': typeof DefaultAboutUsLazyRoute
  '/': typeof DefaultIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_default': typeof DefaultRouteWithChildren
  '/_auth/dashboard': typeof AuthDashboardLazyRoute
  '/_default/about-us': typeof DefaultAboutUsLazyRoute
  '/_default/': typeof DefaultIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/dashboard' | '/about-us' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/dashboard' | '/about-us' | '/'
  id:
    | '__root__'
    | '/_auth'
    | '/_default'
    | '/_auth/dashboard'
    | '/_default/about-us'
    | '/_default/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  DefaultRoute: typeof DefaultRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_default': {
      id: '/_default'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DefaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_default/': {
      id: '/_default/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DefaultIndexLazyRouteImport
      parentRoute: typeof DefaultRoute
    }
    '/_default/about-us': {
      id: '/_default/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof DefaultAboutUsLazyRouteImport
      parentRoute: typeof DefaultRoute
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardLazyRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthDashboardLazyRoute: typeof AuthDashboardLazyRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthDashboardLazyRoute: AuthDashboardLazyRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface DefaultRouteChildren {
  DefaultAboutUsLazyRoute: typeof DefaultAboutUsLazyRoute
  DefaultIndexLazyRoute: typeof DefaultIndexLazyRoute
}

const DefaultRouteChildren: DefaultRouteChildren = {
  DefaultAboutUsLazyRoute: DefaultAboutUsLazyRoute,
  DefaultIndexLazyRoute: DefaultIndexLazyRoute,
}

const DefaultRouteWithChildren =
  DefaultRoute._addFileChildren(DefaultRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  DefaultRoute: DefaultRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
